# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            target
            package.json
            jsr.json
          retention-days: 1

  push:
    name: Push ${{ github.ref }}
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: build
      - name: Fetch deps
        run: npm ci
      - name: Run tests
        run: npm run test

#      - name: Codeclimate
#        if: github.ref == 'refs/heads/main'
#        uses: paambaati/codeclimate-action@v4.0.0
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#        with:
#          coverageLocations: |
#            ${{github.workspace}}/target/coverage/lcov.info:lcov

      - name: Semantic Release (npm)
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_BRANCH: 'main'
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_COMMITTER_EMAIL }}
        run: npx zx-semrel

  pr:
    if: github.event_name == 'pull_request'
    needs: build
    name: PR (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 22 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: build
      - name: Fetch deps
        run: npm ci
      - name: Run all tests
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 22
        run: npm run test
        timeout-minutes: 1

      - name: Run units
        if: matrix.os != 'ubuntu-latest' && matrix.node-version != 22
        run: npm run test:unit
        timeout-minutes: 1
